---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafdrop
  name: kafdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
      - image: obsidiandynamics/kafdrop:4.0.1
        name: kafdrop
        ports:
        - containerPort: 9000
        env:
        - name: KAFKA_BROKERCONNECT
          value: my-cluster-kafka-bootstrap:9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop
spec:
  selector:
    app: kafdrop
  ports:
  - name: kafdrop
    port: 9000