---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.9.0
    metadataVersion: 3.9-IV0
    listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
    - name: external
      port: 9094
      type: ingress
      tls: true
      configuration:
        class: nginx
        brokerCertChainAndKey:
          secretName: my-cluster-lets-encrypt
          certificate: tls.crt
          key: tls.key
        bootstrap:
          host: bootstrap.example.com
        brokers:
        - broker: 0
          host: broker-0.example.com
        - broker: 1
          host: broker-1.example.com
        - broker: 2
          host: broker-2.example.com
    config:
      auto.create.topics.enable: 'false'
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
  entityOperator:
    topicOperator: {}
    userOperator: {}